name:                advent2020
version:             0.1.0.0
github:              "oguimbal/advent2020"
license:             BSD3
author:              "Olivier guimbal"

dependencies:
- base >= 4.7 && < 5
- directory
- vector
- split
- containers

library:
  source-dirs: .


executables:
  advent:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
